#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d " 1 " " 2 " " 3 " " 4 " " 5 " " 6 " " 7 " " 8 " " 9 " " 10 "

bspc config border_width	3
bspc config window_gap		5

bspc config split_ratio          0.5
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config presel_feedback_color "#FFFFFF"
# border
bspc config focused_border_color        "#ff0000"
bspc config normal_border_color         "#808080"
bspc config active_border_color         "#808080"

# set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# bar
~/.config/polybar/launch.sh &

# notifications
/usr/bin/dunst &

# wallpaper
~/.fehbg &

# idk
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# picom
picom -b --config ~/.config/picom/picom.conf &

# Network Applet
nm-applet --indicator &

# xfce4-clipman
xfce4-clipman &

# Cursor
xsetroot -cursor_name left_ptr &

# this is here to unbreak polybar
bspc config right_padding 0

# simplescreenrecorder
simplescreenrecorder --start-hidden &

# hp systray
hp-systray &
