#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# keeb layout
setxkbmap -model acer_laptop -layout de -variant nodeadkeys -option ctrl:nocaps compose:lctrl

# disable touchpad
xinput disable "ELAN0504:01 04F3:3091 Touchpad"

# polkit
#/usr/libexec/polkit-gnome-authentication-agent-1 &

# Get internal monitor (eDP)
INTERNAL=$(xrandr | awk '/ connected/ {print $1}' | grep -E '^eDP')

# Get external monitor (first connected that isn't eDP)
EXTERNAL=$(xrandr | awk '/ connected/ {print $1}' | grep -vE '^eDP' | head -n1)

# Assign desktops
bspc monitor "$INTERNAL" -d " 1 " " 2 " " 3 " " 4 " " 5 "

if [ -n "$EXTERNAL" ]; then
    bspc monitor "$EXTERNAL" -d " 6 " " 7 " " 8 " " 9 " " 10 "
fi

bspc config border_width 3
bspc config window_gap   5

bspc config split_ratio 0.5
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc config presel_feedback_color "#FFFFFF"
# border
bspc config focused_border_color "#ff0000"
bspc config normal_border_color  "#808080"
bspc config active_border_color  "#808080"

# set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# wallpaper
~/.fehbg &

# idk
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Network Applet
nm-applet --indicator &

# pipewire
#pipewire &
#pipewire-pulse &
#wireplumber &

# Cursor
xsetroot -cursor_name left_ptr &

# simplescreenrecorder
simplescreenrecorder --start-hidden &

# bar
~/.config/polybar/launch.sh &

# max volume script
~/.config/bspwm/maxvolume.sh &

# tablet
~/.config/bspwm/tablet.sh

# picom
picom -b -f --config ~/.config/picom/picom.conf &

# emacs
emacs --daemon
